/*
	This file contains a Gin handler to deal with & record links generated by the linkr package
*/

package main

import (
	"fmt"

	"github.com/calebhiebert/gobbl-starter-bot/bdb"
	"github.com/calebhiebert/gobbl-starter-bot/linkr"
	"github.com/gin-gonic/gin"
)

// GHLinkr is a gin handler that can process linkr links
func GHLinkr(c *gin.Context) {
	if c.Query("d") == "" {
		c.JSON(400, gin.H{"error": "missing query param \"d\""})
		return
	}

	decodedLink, err := linkr.Decode(c.Query("d"))
	if err != nil {
		c.JSON(400, gin.H{"error": "invalid linkr data param", "ctx": err})
		return
	}

	// Save to user action
	db := bdb.GDB(c)

	err = db.CreateUserActionURL(decodedLink.PSID, decodedLink.RedirectTo)
	if err != nil {
		fmt.Println("LINKR DB ERR TO USER ACTIONS", err)
	}

	c.Redirect(303, decodedLink.RedirectTo)
}
